### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by iclems** [bufferapp/buffer-safari#4]
Using Safari Version 8.0.2 (10600.3.5). 

Login only works while on Buffer site.

**Comment by Manhazito** [comment]
Hi, @djfarrelly. It's happening again… :-/

**Comment by mrdoro** [comment]
Same as Manhazito. Cant login after upgrade to mac os high sierra

**Comment by taglia** [comment]
Same issue with Safari 11.0.2 (13604.4.7.1.3), on macOS 10.13.2 (17C88). Impossible to log in, neither using auth providers nor with email and password.

**Comment by mrdoro** [comment]
As a workaround for me (passed twice) was to remove a Safari setting Folder  from ~/Library/

**Comment by taglia** [comment]
Another workaround is to open the extension preferences and set it to open in a new tab, worked consistently for me.

**Comment by A-Farmer** [comment]
Hey there! Sorry for all the trouble you've been seeing with the Buffer Extension within Safari. Upon digging in, it appears that this is related to Safari's use of cookies within a 3rd Party context and how Buffer requires a '3rd Party' cookie for user authentication. Having the extension open in a new tab would then allow the cookie to be reference in a 1st party context (within the Buffer domain) and the authentication would work.

If you are experiencing this issue, please reach out to us at hello@buffer.com. Our support team currently doesn't monitor GitHub for reports like this and I'd hate for things to go missing or go unreplied to. Thanks!

**Comment by notasausage** [comment]
This is still an issue, FYI. I am signed into Buffer in Safari, but yet the extension says I need to sign in, and not one of the options actually allows me to sign in. They just open a popup window which then closes automatically.

**Comment by stianulriksen** [comment]
+1 I've been experiencing this for weeks...

**Comment by stianulriksen** [comment]
Thank you for the quick response. I changed from overlay to "open in new tab", and that solved my problem.

**Comment by jamesware** [comment]
Hi @A-Farmer : I tried changing the overlay/new tab settings, and this has not resolved it.

I emailed hello@buffer.com, but received an auto-reply saying that email support is now limited to paying customers, and I am still evaluating on the free version.  The email pointed to FAQs, but I can't find anything there.

I'm not sure how else to connect for advice.

**Comment by digitall-it** [comment]
+1 Hello, I'm a on a paying tier but on Mac Safari extension I can't login.

**Comment by notasausage** [comment]
The only way to fix this is to disable the **Prevent cross-site tracking** option in Safari, which I feel is an unacceptable approach to this issue. The folks at Buffer need to reopen this and the similar #9 issue and fix this properly.

**Comment by rdelrossi** [comment]
Thank you @notasausage. After so much aggravation with this problem, your solution resolves the issue. But I agree, the solution comes at a high price. @A-Farmer, would appreciate hearing from Buffer folks on resolving this fundamental issue.
